name: Release

#on:
#  push:
#    tags:
#      - "day-*"
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MTOOLS_VERSION: 4.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: mtools build-essential nasm
          version: 1.0
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
      - name: Build
        run: |
          make build \
            RUNS_ON=github-actions
        working-directory: ./gogobikeos
      #- name: Release
      #  uses: softprops/action-gh-release@v1
      #  if: startsWith(github.ref, 'refs/tags/')
      #  with:
      #    files: gogobikeos/gogobikeos.img
